FROM node:18-alpine

WORKDIR /app

COPY package.json package-lock.json* ./

RUN rm -rf node_modules && \
    npm cache clean --force && \
    npm install --legacy-peer-deps

COPY . .

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host"]